### ISSUE TITLE
HTT library UI design

### ISSUE THREAD

**Issue by lekzen** [UBT-Designers/Connect-Web-App#2]
@lulomunoz 

![lybrary](https://cloud.githubusercontent.com/assets/22043109/18333068/69f3d2ba-759e-11e6-8db8-bb57f292321c.jpg)

if you have ideas for UI please message me

CC: @ChristopherChuckA @kennethgaerlan

**Comment by ChristopherChuckA** [comment]
@lekzen will get back to you shortly :+1:

**Comment by lekzen** [comment]
![lybrary](https://cloud.githubusercontent.com/assets/22043109/18370118/337373e8-765d-11e6-943e-e701a9a233c1.jpg)
update

@ChristopherChuckA  @kennethgaerlan @lulomunoz
